(****************************************************************************************************)
(* File automalically generated by FeynRules -                                                      *)
(* date and time of generation : Mon 15 Sep 2025 14:33:37                                           *)
(* FeynRules model information :                                                                    *)
(*   Authors: A. Vasquez                                                                            *)
(*   Version: 1.final                                                                               *)
(*   Date: 2025                                                                                     *)
(*   Institutions: Bonn U.                                                                          *)
(*   Emails:                                                                                        *)
(****************************************************************************************************)

(*****  This file contains the fields that  appear in the Feynman Rules  *****)


AN$ModelName = "chromo";

AN$GaugeGroups = {{U1Y, Abelian}, {SU2L, NonAbelian}, {SU3C, NonAbelian}};

AN$Fields = {G0, GP, H, G, ghG, b, t};

AN$antiFields = {GPbar, ghGbar, bbar, tbar};

AN$Fermions = {b, t, bbar, tbar};

AN$Bosons = {G0, GP, H, G, GPbar};

AN$VectorFields = {G};

AN$ScalarFields = {G0, GP, H, ghG, GPbar, ghGbar};

AN$xFermions = {b, t};

AN$yFermions = {bbar, tbar};

AN$NoCouplings = 48;

AN$Parameters = {aEWM1, Gf, aS, ymdo, ymup, yms, ymc, ymb, ymt, yme, ymm, ymtau, cabi, aEW, sw2, ee, cw, sw, gw, g1, gs, vev, lam, muH, yl, yu, yd, CKM, ctp, cpG, ctG, cG, cEFT, yb, yt, ytau, MZ, MW, MH};

AN$Masses = {{G0, MZ}, {GP, MW}, {H, MH}, {b, MB}, {t, MT}, {GPbar, MW}, {bbar, MB}, {tbar, MT}};

AN$IndicesInFR = {Gluon, Colour};

AN$FieldsClassified = {{{Gluon, G}, {Gluon, ghG}, {Gluon, ghGbar}}, {{Colour, b}, {Colour, t}, {Colour, bbar}, {Colour, tbar}}};

AN$StructureConstantsList = {Eps, f};

AN$GeneratorsList = {Ta, FSU2L, T, FSU3C};

AN$ExternalParameters = {{aEWM1, 127.9`}, {Gf, 0.0000116637`}, {aS, 0.1184`}, {ymdo, 0.00504`}, {ymup, 0.00255`}, {yms, 0.101`}, {ymc, 1.27`}, {ymb, 4.7`}, {ymt, 172}, {yme, 0.000511`}, {ymm, 0.10566`}, {ymtau, 1.777`}, {cabi, 0.227736`}, {ctp, 1}, {cpG, 1}, {ctG, 1}, {cG, 1}, {cEFT, 1}};

