(****************************************************************************************************)
(* File automalically generated by FeynRules -                                                      *)
(* date and time of generation : Wed 27 Aug 2025 11:03:10                                           *)
(* FeynRules model information :                                                                    *)
(*   Authors: C. Duhr, P. Mukherjee, A. Vasquez                                                     *)
(*   Version: 1.0                                                                                   *)
(*   Date: 25. 08. 2025                                                                             *)
(*   Institutions: Universitat Bonn,  Universitat Hamburg                                           *)
(*   Emails: cduhr@uni-bonn.de, pooja.mukherjee@desy.de, avasquez@uni-bonn.de                       *)
(****************************************************************************************************)

(*****  This file contains the fields that  appear in the Feynman Rules  *****)


AN$ModelName = "QED";

AN$GaugeGroups = {{U1Y, Abelian}};

AN$Fields = {e, A, mu, ta, t};

AN$antiFields = {ebar, mubar, tabar, tbar};

AN$Fermions = {e, mu, ta, t, ebar, mubar, tabar, tbar};

AN$Bosons = {A};

AN$VectorFields = {A};

AN$ScalarFields = {};

AN$xFermions = {e, mu, ta, t};

AN$yFermions = {ebar, mubar, tabar, tbar};

AN$NoCouplings = 2;

AN$Parameters = {ee};

AN$Masses = {{e, Me}, {mu, MMU}, {ta, MTA}, {t, MT}, {ebar, Me}, {mubar, MMU}, {tabar, MTA}, {tbar, MT}};

AN$IndicesInFR = {Colour};

AN$FieldsClassified = {{{Colour, t}, {Colour, tbar}}};

AN$StructureConstantsList = {};

AN$GeneratorsList = {};

AN$ExternalParameters = {};

