(****************************************************************************************************)
(* File automalically generated by FeynRules -                                                      *)
(* date and time of generation : Wed 3 Sep 2025 12:47:11                                            *)
(* FeynRules model information :                                                                    *)
(*   Authors: C. Duhr, P. Mukherjee, A. Vasquez                                                     *)
(*   Version: 1.0                                                                                   *)
(*   Date: 25. 08. 2025                                                                             *)
(*   Institutions: Universitat Bonn,  Universitat Hamburg                                           *)
(*   Emails: cduhr@uni-bonn.de, pooja.mukherjee@desy.de, avasquez@uni-bonn.de                       *)
(****************************************************************************************************)

(*****  This file contains the fields that  appear in the Feynman Rules  *****)


AN$ModelName = "sm";

AN$GaugeGroups = {{U1Y, Abelian}, {SU2L, NonAbelian}, {SU3C, NonAbelian}};

AN$Fields = {G0, GP, H, A, ghWm, W, ghWp, ghA, Z, ghZ, ghG, G, t, b, vt, ta, e, mu, c, u, d, s, ve, vm};

AN$antiFields = {GPbar, ghWmbar, Wbar, ghWpbar, ghAbar, ghZbar, ghGbar, tbar, bbar, vtbar, tabar, ebar, mubar, cbar, ubar, dbar, sbar, vebar, vmbar};

AN$Fermions = {t, b, vt, ta, e, mu, c, u, d, s, ve, vm, tbar, bbar, vtbar, tabar, ebar, mubar, cbar, ubar, dbar, sbar, vebar, vmbar};

AN$Bosons = {G0, GP, H, A, W, Z, G, GPbar, Wbar};

AN$VectorFields = {A, W, Z, G, Wbar};

AN$ScalarFields = {G0, GP, H, ghWm, ghWp, ghA, ghZ, ghG, GPbar, ghWmbar, ghWpbar, ghAbar, ghZbar, ghGbar};

AN$xFermions = {t, b, vt, ta, e, mu, c, u, d, s, ve, vm};

AN$yFermions = {tbar, bbar, vtbar, tabar, ebar, mubar, cbar, ubar, dbar, sbar, vebar, vmbar};

AN$NoCouplings = 70;

AN$Parameters = {aEWM1, Gf, aS, ymdo, ymup, yms, ymc, ymb, ymt, yme, ymm, ymtau, cabi, aEW, sw2, ee, cw, sw, gw, g1, gs, vev, lam, muH, yl, yu, yd, CKM, yb, yt, ytau, MZ, MW, MH};

AN$Masses = {{G0, MZ}, {GP, MW}, {H, MH}, {ghWm, MW}, {W, MW}, {ghWp, MW}, {Z, MZ}, {ghZ, MZ}, {t, MT}, {b, MB}, {ta, MTA}, {GPbar, MW}, {ghWmbar, MW}, {Wbar, MW}, {ghWpbar, MW}, {ghZbar, MZ}, {tbar, MT}, {bbar, MB}, {tabar, MTA}};

AN$IndicesInFR = {Gluon, Colour};

AN$FieldsClassified = {{{Gluon, ghG}, {Gluon, G}, {Gluon, ghGbar}}, {{Colour, t}, {Colour, b}, {Colour, c}, {Colour, u}, {Colour, d}, {Colour, s}, {Colour, tbar}, {Colour, bbar}, {Colour, cbar}, {Colour, ubar}, {Colour, dbar}, {Colour, sbar}}};

AN$StructureConstantsList = {Eps, f};

AN$GeneratorsList = {Ta, FSU2L, T, FSU3C};

AN$ExternalParameters = {{aEWM1, 127.9`}, {Gf, 0.0000116637`}, {aS, 0.1184`}, {ymdo, 0.00504`}, {ymup, 0.00255`}, {yms, 0.101`}, {ymc, 1.27`}, {ymb, 4.7`}, {ymt, 172}, {yme, 0.000511`}, {ymm, 0.10566`}, {ymtau, 1.777`}, {cabi, 0.227736`}};

